// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADVgvZm0XHVbvBZtkZZa3F3P3COO5jTds',
    appId: '1:869932988389:web:0a696283656d82a4e8e10c',
    messagingSenderId: '869932988389',
    projectId: 'ptma-9c13f',
    authDomain: 'ptma-9c13f.firebaseapp.com',
    storageBucket: 'ptma-9c13f.appspot.com',
    measurementId: 'G-8XS2CMMV1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2YCbbdy3OYHEQwa7JgL2mmW-tZFUfvpA',
    appId: '1:869932988389:android:6e5cd7913936addee8e10c',
    messagingSenderId: '869932988389',
    projectId: 'ptma-9c13f',
    storageBucket: 'ptma-9c13f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-2R3xlBGl_NRT4CQzmOUKf49uK4C6S78',
    appId: '1:869932988389:ios:72b015d329ab9503e8e10c',
    messagingSenderId: '869932988389',
    projectId: 'ptma-9c13f',
    storageBucket: 'ptma-9c13f.appspot.com',
    androidClientId: '869932988389-7q2lamnk203ebb3jta20pvl85ue4dmkr.apps.googleusercontent.com',
    iosClientId: '869932988389-0alv5onpl2jcg2si0qt69p9jal73vcct.apps.googleusercontent.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-2R3xlBGl_NRT4CQzmOUKf49uK4C6S78',
    appId: '1:869932988389:ios:72b015d329ab9503e8e10c',
    messagingSenderId: '869932988389',
    projectId: 'ptma-9c13f',
    storageBucket: 'ptma-9c13f.appspot.com',
    androidClientId: '869932988389-7q2lamnk203ebb3jta20pvl85ue4dmkr.apps.googleusercontent.com',
    iosClientId: '869932988389-0alv5onpl2jcg2si0qt69p9jal73vcct.apps.googleusercontent.com',
    iosBundleId: 'com.example.admin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADVgvZm0XHVbvBZtkZZa3F3P3COO5jTds',
    appId: '1:869932988389:web:0a696283656d82a4e8e10c',
    messagingSenderId: '869932988389',
    projectId: 'ptma-9c13f',
    authDomain: 'ptma-9c13f.firebaseapp.com',
    storageBucket: 'ptma-9c13f.appspot.com',
    measurementId: 'G-8XS2CMMV1B',
  );

}